### ISSUE TITLE
Incorrect results when used from multiple threads concurrently.

### ISSUE THREAD

**Issue by selaux** [toptensoftware/RichTextKit#22]
Hi,

when using RichTextKit within an ASP.NET application for PDF export, we noticed that in a multi-threaded context RichTextKit is not behaving properly. We noticed multiple exceptions as well as weird issues with TextBlocks being rendered in different styles than the ones that were defined for the specific text block.

First of all my question would be: Should this usecase (using RichTextKit from multiple threads) be supported? If so, what follows is some example code to reproduce issues and some exceptions that occurred for me.

<details>
  <summary>Open to view test example</summary>

```csharp
using System;
using System.IO;
using System.Threading;
using SkiaSharp;
using Topten.RichTextKit;

namespace RichTextKitIssue
{
    class Program
    {
        private const int MAX_THREADS = 10;

        static void Main(string[] args)
        {
            for (var i = 0; i < MAX_THREADS; i++)
            {
                var i1 = i;
                Thread thread = new Thread(() =>
                {
                    var index = i1;
                    Console.WriteLine("Thread started");
                    var text = GetLayout();
                    var bitmap = Render(text);
                    var path = $"{index.ToString()}.png";
                    using (var file = File.OpenWrite(path))
                    {
                        bitmap.Encode(file, SKEncodedImageFormat.Png, 90);
                    }
                });
                thread.Start();
            }
        }

        public static RichString GetLayout()
        {
            var r = new RichString();
            r = r.FontSize(64).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 64 Bold");
            r = r.Paragraph().FontSize(48).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 48 Bold");
            r = r.Paragraph().FontSize(32).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 32 Bold");
            r = r.Paragraph().FontSize(24).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 24 Bold");
            r = r.Paragraph().FontSize(18).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 18 Bold");
            r = r.Paragraph().FontSize(12).FontWeight((int) SKFontStyleWeight.Bold).Add("Some Text in 12 Bold");
            r = r.Paragraph().FontSize(64).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 64 Normal");
            r = r.Paragraph().FontSize(48).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 48 Normal");
            r = r.Paragraph().FontSize(32).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 32 Normal");
            r = r.Paragraph().FontSize(24).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 24 Normal");
            r = r.Paragraph().FontSize(18).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 18 Normal");
            r = r.Paragraph().FontSize(12).FontWeight((int) SKFontStyleWeight.Normal).Add("Some Text in 12 Normal");
            r = r.Paragraph().FontSize(64).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 64 Light");
            r = r.Paragraph().FontSize(48).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 48 Light");
            r = r.Paragraph().FontSize(32).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 32 Light");
            r = r.Paragraph().FontSize(24).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 24 Light");
            r = r.Paragraph().FontSize(18).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 18 Light");
            r = r.Paragraph().FontSize(12).FontWeight((int) SKFontStyleWeight.Light).Add("Some Text in 12 Light");
            return r;
        }

        public static SKBitmap Render(RichString r)
        {
            var bitmap = new SKBitmap(1080, 1920);
            var canvas = new SKCanvas(bitmap);
            canvas.Clear(SKColors.White);
            r.Paint(canvas);
            return bitmap;
        }
    }
}
```
</details>

Exceptions that were noticed by just running the example:

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Topten.RichTextKit.StyleManager.Update(String fontFamily, Nullable`1 fontSize, Nullable`1 fontWeight, Nullable`1 fontItalic, Nullable`1 underline, Nullable`1 strikeThrough, Nullable`1 lineHeight, Nullable`1 textColor, Nullable`1 letterSpacing, Nullable`1 fontVariant, Nullable`1 textDirection)
```

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Arial.64.700.False.None.None.1.#ff000000.0.Normal.Auto
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Topten.RichTextKit.StyleManager.Update(String fontFamily, Nullable`1 fontSize, Nullable`1 fontWeight, Nullable`1 fontItalic, Nullable`1 underline, Nullable`1 strikeThrough, Nullable`1 lineHeight, Nullable`1 textColor, Nullable`1 letterSpacing, Nullable`1 fontVariant, Nullable`1 textDirection)
```

Also there seem to be some rendering issues where text styles are mixed up. The following is an example for this. This is the output of the above sample code when it is rendered correctly:

![expected](https://user-images.githubusercontent.com/848854/91065131-6a08c600-e630-11ea-9eed-09e27e67db5b.png)

Here is an example of the above code with rendering issues, where the "Text in 32 Normal" is unfortunately not rendered in 32 normal

![got](https://user-images.githubusercontent.com/848854/91065149-6ecd7a00-e630-11ea-96e2-614605791cc8.png)

**Comment by toptensoftware** [comment]
Hi @selaux,

Thanks for the detailed fault report.  In general RichTextKit should be thread safe so long as you're not using objects across threads. However, I just did a quick review of RichString and there's an issue where it uses a shared instance of the style manager regardless of thread.  So yes, this is a bug in RichTextKit... leave it with me and I'll sort out a fix.

Brad

**Comment by toptensoftware** [comment]
Build 0.3.132 (available on nuget now) should fix this.

**Comment by selaux** [comment]
Zes. I can confirm that this is not happening anymore with the new version. Thanks for the quick reaction and fix.
